//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWMM_CAT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWMM_CAT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USC00010008 31.5702 -85.2482
        ///USC00010063 34.2553 -87.1814
        ///USC00010140 32.2322 -87.4104
        ///USC00010252 31.3071 -86.5226
        ///USC00010369 33.2941 -85.7788
        ///USC00010390 34.7752 -86.9508
        ///USC00010402 31.182 -87.439 
        ///USC00010425 32.5992 -85.4653
        ///USC00010748 33.6971 -87.6488
        ///USC00010957 34.2008 -86.1633
        ///USC00011099 34.9786 -85.8008
        ///USC00012124 32.8622 -85.7358
        ///USC00012172 30.2505 -88.0775
        ///USC00012377 31.2833 -85.4 
        ///USC00012675 31.2975 -85.8996
        ///USC00013043 34.4406 -85.7236
        ///USC00013519 31.7901 -86.6087
        ///USC00013620 34.2314 -8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string evap {
            get {
                return ResourceManager.GetString("evap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	5yrann_mm	10yrann_mm	15yrann_mm	30yrann_mm	50yrann_mm	100yrann_mm
        ///USC00010008	131.32	152.4	163.83	183.64	197.1	215.65
        ///USC00010063	101.6	115.06	122.43	135.38	144.53	157.23
        ///USC00010140	125.22	146.3	158.5	179.83	195.07	216.66
        ///USC00010252	144.53	187.71	217.17	279.91	334.26	427.23
        ///USC00010369	116.08	135.64	146.56	166.12	179.83	199.14
        ///USC00010390	106.43	125.22	135.89	155.19	168.91	188.47
        ///USC00010402	146.56	171.96	186.69	212.85	231.65	258.32
        ///USC00010425	113.54	131.32	140.97	156.72	167.13	181.1
        ///USC0001074 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GEVdepth_historical {
            get {
                return ResourceManager.GetString("GEVdepth_historical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	5yrann_mm	10yrann_mm	15yrann_mm	30yrann_mm	50yrann_mm	100yrann_mm
        ///USC00010008	132.64	154.15	165.89	186.36	200.42	219.96
        ///USC00010063	103.41	117.43	125.17	138.87	148.66	162.37
        ///USC00010140	126.74	148.48	161.13	183.41	199.48	222.49
        ///USC00010252	145.73	189.96	220.28	285.14	341.72	439.15
        ///USC00010369	118.04	137.94	149.08	169.07	183.16	203.08
        ///USC00010390	108.55	127.96	139.04	159.17	173.57	194.25
        ///USC00010402	147.76	174.09	189.51	217.11	237.23	266.12
        ///USC00010425	115.16	133.22	143.07	159.18	169.92	184.42
        ///USC0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GEVdepth2035LessStormy {
            get {
                return ResourceManager.GetString("GEVdepth2035LessStormy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	5yrann_mm	10yrann_mm	15yrann_mm	30yrann_mm	50yrann_mm	100yrann_mm
        ///USC00010008	142.74	167.12	180.66	204.65	221.54	245.51
        ///USC00010063	110.28	125.83	134.46	149.83	160.92	176.58
        ///USC00010140	136.12	160.48	174.81	200.3	218.97	246.0
        ///USC00010252	157.04	205.95	239.71	312.41	376.41	487.47
        ///USC00010369	126.25	148.86	161.74	185.15	202.02	226.32
        ///USC00010390	115.57	137.02	149.36	171.89	188.22	211.88
        ///USC00010402	159.26	188.66	206.03	237.46	260.67	294.43
        ///USC00010425	123.48	144.16	155.66	174.88	188.07	206.33
        ///USC000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GEVdepth2035Stormy {
            get {
                return ResourceManager.GetString("GEVdepth2035Stormy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	5yrann_mm	10yrann_mm	15yrann_mm	30yrann_mm	50yrann_mm	100yrann_mm
        ///USC00010008	133.9	155.81	167.84	188.95	203.57	224.03
        ///USC00010063	105.12	119.66	127.77	142.18	152.56	167.24
        ///USC00010140	128.16	150.55	163.63	186.79	203.66	227.99
        ///USC00010252	146.85	192.08	223.21	290.1	348.77	450.38
        ///USC00010369	119.9	140.13	151.47	171.86	186.31	206.8
        ///USC00010390	110.58	130.57	142.02	162.92	177.98	199.72
        ///USC00010402	148.9	176.12	192.16	221.15	242.51	273.51
        ///USC00010425	116.69	135.03	145.04	161.51	172.55	187.55
        ///USC000107 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GEVdepth2060LessStormy {
            get {
                return ResourceManager.GetString("GEVdepth2060LessStormy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	5yrann_mm	10yrann_mm	15yrann_mm	30yrann_mm	50yrann_mm	100yrann_mm
        ///USC00010008	153.55	181.04	196.58	224.52	244.67	273.78
        ///USC00010063	118.49	136.01	145.85	163.5	176.41	194.9
        ///USC00010140	146.42	173.88	190.23	219.65	241.58	273.77
        ///USC00010252	168.86	223.2	261.04	343.14	416.26	544.42
        ///USC00010369	135.86	161.38	176.1	203.16	223.03	252.01
        ///USC00010390	124.22	148.19	162.09	187.69	206.49	234.02
        ///USC00010402	171.28	204.46	224.33	260.74	288.12	328.58
        ///USC00010425	132.88	156.32	169.56	192.07	207.9	230.18
        ///USC000107 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GEVdepth2060Stormy {
            get {
                return ResourceManager.GetString("GEVdepth2060Stormy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWMM-CAT is a utility that adds location-specific climate change adjustments to a Storm Water Management Model (SWMM) project file. Adjustments can be applied on a monthly basis to air temperature, evaporation rates, and precipitation, as well as to the 24-hour design storm at different recurrence intervals. The source of these adjustments are global climate change models run as part of the World Climate Research Programme (WCRP) Coupled Model Intercomparison Project Phase 3 (CMIP3) archive. Downscaled resu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	SumAnnual
        ///USC00010008	0.071	0.095	0.137	0.181	0.219	0.233	0.231	0.215	0.183	0.136	0.095	0.071	56.936
        ///USC00010063	0.054	0.075	0.114	0.163	0.198	0.222	0.224	0.210	0.173	0.123	0.078	0.054	51.421
        ///USC00010140	0.068	0.092	0.134	0.181	0.217	0.236	0.236	0.222	0.186	0.137	0.093	0.067	57.012
        ///USC00010252	0.078	0.104	0.150	0.195	0.233	0.247	0.243	0.225	0.193	0.148	0.104	0.078	60.938
        ///USC00010369	0.060	0.083	0.125	0.173	0.208	0.230	0.231	0.213	0.178	0.128	0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HET_2035Central {
            get {
                return ResourceManager.GetString("HET_2035Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	SumAnnual
        ///USC00010008	0.072	0.096	0.138	0.182	0.221	0.235	0.232	0.215	0.183	0.137	0.095	0.072	57.281
        ///USC00010063	0.053	0.075	0.115	0.163	0.199	0.224	0.227	0.212	0.174	0.124	0.078	0.054	51.790
        ///USC00010140	0.068	0.092	0.135	0.182	0.219	0.239	0.239	0.224	0.187	0.139	0.093	0.067	57.437
        ///USC00010252	0.079	0.105	0.151	0.197	0.236	0.250	0.246	0.226	0.194	0.149	0.105	0.078	61.456
        ///USC00010369	0.060	0.083	0.125	0.173	0.210	0.233	0.234	0.215	0.178	0.129	0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HET_2035HotDry {
            get {
                return ResourceManager.GetString("HET_2035HotDry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	SumAnnual
        ///USC00010008	0.071	0.096	0.137	0.181	0.219	0.232	0.230	0.214	0.182	0.135	0.094	0.071	56.764
        ///USC00010063	0.053	0.075	0.114	0.162	0.198	0.221	0.223	0.209	0.172	0.122	0.077	0.053	51.178
        ///USC00010140	0.067	0.093	0.134	0.181	0.218	0.236	0.235	0.220	0.185	0.136	0.092	0.067	56.822
        ///USC00010252	0.078	0.105	0.149	0.196	0.234	0.247	0.242	0.223	0.192	0.147	0.104	0.078	60.799
        ///USC00010369	0.060	0.083	0.124	0.173	0.208	0.229	0.230	0.212	0.176	0.128	0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HET_2035WetWarm {
            get {
                return ResourceManager.GetString("HET_2035WetWarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	SumAnnual
        ///USC00010008	0.074	0.098	0.141	0.186	0.226	0.239	0.237	0.222	0.189	0.141	0.098	0.073	58.635
        ///USC00010063	0.056	0.078	0.118	0.169	0.205	0.229	0.231	0.217	0.178	0.128	0.081	0.056	53.253
        ///USC00010140	0.070	0.095	0.139	0.187	0.224	0.242	0.242	0.229	0.192	0.143	0.097	0.070	58.810
        ///USC00010252	0.081	0.107	0.154	0.201	0.240	0.253	0.249	0.232	0.199	0.153	0.108	0.080	62.729
        ///USC00010369	0.063	0.086	0.129	0.178	0.215	0.236	0.237	0.220	0.184	0.133	0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HET_2060Central {
            get {
                return ResourceManager.GetString("HET_2060Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	SumAnnual
        ///USC00010008	0.075	0.100	0.143	0.188	0.229	0.243	0.239	0.222	0.189	0.142	0.100	0.075	59.310
        ///USC00010063	0.056	0.078	0.120	0.169	0.207	0.234	0.236	0.221	0.181	0.130	0.082	0.056	53.976
        ///USC00010140	0.071	0.096	0.141	0.189	0.228	0.248	0.247	0.231	0.194	0.145	0.097	0.070	59.644
        ///USC00010252	0.082	0.109	0.157	0.204	0.245	0.259	0.254	0.234	0.201	0.156	0.110	0.081	63.744
        ///USC00010369	0.062	0.087	0.130	0.179	0.218	0.243	0.243	0.223	0.185	0.135	0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HET_2060HotDry {
            get {
                return ResourceManager.GetString("HET_2060HotDry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	SumAnnual
        ///USC00010008	0.073	0.099	0.140	0.186	0.226	0.238	0.235	0.219	0.187	0.139	0.097	0.073	58.303
        ///USC00010063	0.055	0.078	0.117	0.167	0.205	0.227	0.228	0.214	0.177	0.126	0.080	0.056	52.777
        ///USC00010140	0.069	0.096	0.138	0.187	0.225	0.242	0.240	0.225	0.190	0.141	0.095	0.069	58.440
        ///USC00010252	0.081	0.109	0.153	0.202	0.241	0.253	0.248	0.228	0.197	0.151	0.107	0.080	62.455
        ///USC00010369	0.062	0.087	0.128	0.178	0.215	0.236	0.235	0.217	0.182	0.132	0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HET_2060WetWarm {
            get {
                return ResourceManager.GetString("HET_2060WetWarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	SumAnnual
        ///USC00010008	0.069	0.092	0.133	0.176	0.213	0.226	0.224	0.209	0.177	0.131	0.091	0.068	55.153
        ///USC00010063	0.051	0.071	0.110	0.156	0.191	0.214	0.217	0.203	0.166	0.117	0.074	0.051	49.501
        ///USC00010140	0.065	0.089	0.130	0.175	0.210	0.229	0.229	0.215	0.180	0.132	0.089	0.065	55.126
        ///USC00010252	0.076	0.101	0.145	0.190	0.226	0.240	0.237	0.218	0.187	0.142	0.100	0.075	59.057
        ///USC00010369	0.058	0.080	0.120	0.167	0.201	0.223	0.224	0.206	0.171	0.123	0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HET_historical {
            get {
                return ResourceManager.GetString("HET_historical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	Ann
        ///USC00010008	2.14	-0.47	3.68	1.32	-1.68	4.6	-2.5	-4.47	5.05	6.7	-0.61	1.06	0.95
        ///USC00010063	0.77	-3.21	5.86	2.65	-2.63	-2.92	-1.4	-1.01	3.81	-0.75	3.08	1.69	0.58
        ///USC00010140	1.42	-2.68	3.1	1.46	-1.52	1.11	-1.71	-0.11	5.04	6.81	-1.94	1.44	0.8
        ///USC00010252	1.08	-1.67	3.55	-0.05	-1.63	3.9	-2.96	-5.4	5.58	8.41	-1.81	1.79	0.44
        ///USC00010369	0.61	-2.36	5.39	1.7	0.54	3.17	-0.68	-0.39	4.03	4.78	2.1	0.72	1.43
        ///USC00010390	0.54	-3.33	6.79	3.13	-3.1	-2.35	-0.63	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PREC2035Central {
            get {
                return ResourceManager.GetString("PREC2035Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	Ann
        ///USC00010008	0.73	-4.74	2.45	-5.43	-0.54	-3.56	-3.75	-0.5	6.12	-1.64	-5.38	-2.27	-1.75
        ///USC00010063	-0.22	0.6	2.22	-0.88	-5.03	-8.51	-8.75	2.57	1.27	-1.08	-3.96	0.5	-1.81
        ///USC00010140	-2.7	-2.93	0.13	-2.65	-6.08	-4.92	-4.47	1.65	6.66	0.03	-6.77	-2.92	-2.26
        ///USC00010252	-2.4	-6.13	-1.82	-2.29	-1.81	-3.91	-6.06	1.46	7.86	4.97	-4.38	-2.3	-1.76
        ///USC00010369	-0.77	-0.77	-0.78	-3.3	-6.8	-8.56	-4.44	0.01	2.72	0.16	-3.48	0.66	-2.17
        ///USC00010390	-1.2	-0.18	2.96 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PREC2035HotDry {
            get {
                return ResourceManager.GetString("PREC2035HotDry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	Ann
        ///USC00010008	0.31	10.51	5.25	3.63	4.27	6.29	2.11	3.47	13.44	4.8	2.13	3.77	5.03
        ///USC00010063	7.05	8.61	9.81	4.51	1.99	2.58	6.52	7.61	13.49	7.86	0.94	4.22	6.21
        ///USC00010140	2.44	8.41	4.73	3.49	7.09	4.91	9.9	7.64	17.92	8.18	-0.42	4.24	6.43
        ///USC00010252	3.6	8.02	5.28	0.69	6.51	8.31	9.55	7.16	18.5	10.03	-0.17	2.78	6.63
        ///USC00010369	3.34	10.58	7.86	5.53	4.42	3.52	3.23	6.32	12.92	3.54	1.95	5.82	5.8
        ///USC00010390	7.5	8.92	9.98	4.08	1.51	3.23	6.06	7.78	11.51	7.3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PREC2035WetWarm {
            get {
                return ResourceManager.GetString("PREC2035WetWarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	Ann
        ///USC00010008	4.18	-0.92	7.18	2.58	-3.27	8.97	-4.88	-8.72	9.86	13.08	-1.2	2.07	1.86
        ///USC00010063	1.51	-6.27	11.44	5.17	-5.12	-5.69	-2.74	-1.98	7.43	-1.46	6.01	3.3	1.14
        ///USC00010140	2.77	-5.23	6.05	2.85	-2.97	2.17	-3.34	-0.22	9.83	13.29	-3.78	2.8	1.56
        ///USC00010252	2.11	-3.26	6.93	-0.1	-3.18	7.62	-5.77	-10.53	10.9	16.42	-3.54	3.49	0.85
        ///USC00010369	1.2	-4.6	10.51	3.32	1.06	6.19	-1.33	-0.75	7.86	9.33	4.1	1.41	2.79
        ///USC00010390	1.05	-6.49	13.24	6.1	-6.04	-4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PREC2060Central {
            get {
                return ResourceManager.GetString("PREC2060Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	Ann
        ///USC00010008	1.43	-9.24	4.78	-10.6	-1.05	-6.94	-7.31	-0.98	11.94	-3.19	-10.51	-4.43	-3.42
        ///USC00010063	-0.44	1.17	4.33	-1.72	-9.81	-16.61	-17.07	5.02	2.48	-2.11	-7.74	0.98	-3.54
        ///USC00010140	-5.27	-5.71	0.25	-5.17	-11.87	-9.59	-8.73	3.23	13.0	0.05	-13.22	-5.7	-4.4
        ///USC00010252	-4.67	-11.97	-3.55	-4.47	-3.53	-7.63	-11.83	2.85	15.34	9.7	-8.54	-4.49	-3.43
        ///USC00010369	-1.49	-1.5	-1.53	-6.44	-13.28	-16.71	-8.66	0.02	5.3	0.31	-6.8	1.29	-4.23
        ///USC00010390	-2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PREC2060HotDry {
            get {
                return ResourceManager.GetString("PREC2060HotDry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	Ann
        ///USC00010008	0.6	20.5	10.24	7.08	8.34	12.28	4.12	6.78	26.23	9.37	4.16	7.35	9.82
        ///USC00010063	13.76	16.8	19.14	8.8	3.88	5.04	12.71	14.85	26.32	15.34	1.83	8.23	12.11
        ///USC00010140	4.77	16.4	9.23	6.8	13.84	9.59	19.31	14.9	34.97	15.95	-0.82	8.27	12.54
        ///USC00010252	7.03	15.64	10.31	1.34	12.7	16.23	18.63	13.98	36.11	19.58	-0.33	5.42	12.95
        ///USC00010369	6.51	20.65	15.33	10.8	8.62	6.86	6.31	12.34	25.21	6.91	3.81	11.36	11.32
        ///USC00010390	14.64	17.4	19.47	7.96	2.9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PREC2060WetWarm {
            get {
                return ResourceManager.GetString("PREC2060WetWarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USC00010008 31.5702 -85.2482
        ///USC00010063 34.2553 -87.1814
        ///USC00010140 32.2322 -87.4104
        ///USC00010252 31.3071 -86.5226
        ///USC00010369 33.2941 -85.7788
        ///USC00010390 34.7752 -86.9508
        ///USC00010402 31.182 -87.439 
        ///USC00010425 32.5992 -85.4653
        ///USC00010748 33.6971 -87.6488
        ///USC00010957 34.2008 -86.1633
        ///USC00011099 34.9786 -85.8008
        ///USC00012124 32.8622 -85.7358
        ///USC00012172 30.2505 -88.0775
        ///USC00012377 31.2833 -85.4 
        ///USC00012675 31.2975 -85.8996
        ///USC00013043 34.4406 -85.7236
        ///USC00013519 31.7901 -86.6087
        ///USC00013620 34.2314 -8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string precip {
            get {
                return ResourceManager.GetString("precip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USC00010008 31.5702 -85.2482
        ///USC00010063 34.2553 -87.1814
        ///USC00010140 32.2322 -87.4104
        ///USC00010252 31.3071 -86.5226
        ///USC00010369 33.2941 -85.7788
        ///USC00010390 34.7752 -86.9508
        ///USC00010402 31.182 -87.439 
        ///USC00010425 32.5992 -85.4653
        ///USC00010748 33.6971 -87.6488
        ///USC00010957 34.2008 -86.1633
        ///USC00011099 34.9786 -85.8008
        ///USC00012124 32.8622 -85.7358
        ///USC00012172 30.2505 -88.0775
        ///USC00012377 31.2833 -85.4 
        ///USC00012675 31.2975 -85.8996
        ///USC00013043 34.4406 -85.7236
        ///USC00013519 31.7901 -86.6087
        ///USC00013620 34.2314 -8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string storm {
            get {
                return ResourceManager.GetString("storm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	Ann
        ///USC00010008	1.6	1.5	1.85	1.94	2.19	2.2	2.2	2.56	2.63	2.48	2.27	1.63	2.09
        ///USC00010063	2.06	1.98	1.88	2.32	2.54	2.44	2.43	2.57	2.61	2.72	2.38	2.17	2.34
        ///USC00010140	1.72	1.63	1.94	2.22	2.23	2.22	2.24	2.53	2.59	2.64	2.45	1.83	2.18
        ///USC00010252	1.65	1.59	1.84	1.92	2.1	2.13	2.07	2.39	2.53	2.45	2.28	1.65	2.05
        ///USC00010369	1.76	1.69	1.83	2.05	2.27	2.25	2.2	2.56	2.83	2.61	2.36	1.75	2.18
        ///USC00010390	2.08	1.99	1.9	2.34	2.58	2.45	2.45	2.61	2.64	2.75	2.38	2.17	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TEMP2035Central {
            get {
                return ResourceManager.GetString("TEMP2035Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	Ann
        ///USC00010008	2.05	2.04	2.11	2.3	2.82	2.9	2.68	2.53	2.68	2.99	2.63	2.36	2.5
        ///USC00010063	1.98	2.04	2.26	2.38	2.81	3.39	3.42	3.22	3.19	3.26	2.77	2.02	2.74
        ///USC00010140	1.9	1.89	2.35	2.48	2.92	3.21	3.07	2.98	3.0	3.22	2.66	1.89	2.63
        ///USC00010252	1.97	2.1	2.43	2.41	2.86	2.98	2.84	2.74	2.83	3.15	2.76	2.08	2.59
        ///USC00010369	1.58	1.96	2.13	2.26	2.77	3.42	3.19	3.12	3.04	3.11	2.69	1.58	2.57
        ///USC00010390	2.29	2.34	2.54	2.58	2.75	3.07	3.32	3.34	3.31	3.28	2.87	2.56 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TEMP2035HotDry {
            get {
                return ResourceManager.GetString("TEMP2035HotDry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	Ann
        ///USC00010008	1.41	1.96	1.56	2.0	2.22	1.95	1.86	1.88	2.17	2.18	1.83	1.8	1.91
        ///USC00010063	1.79	2.0	1.67	2.04	2.48	2.19	1.89	1.96	2.3	2.4	2.06	1.83	2.05
        ///USC00010140	1.35	2.22	1.63	2.18	2.37	2.15	1.85	1.87	2.11	2.21	1.92	1.71	1.96
        ///USC00010252	1.62	2.02	1.59	2.09	2.26	2.02	1.8	1.74	2.02	2.08	1.91	1.68	1.91
        ///USC00010369	1.47	2.01	1.53	2.11	2.36	2.12	1.9	1.98	2.3	2.3	1.91	1.86	1.98
        ///USC00010390	1.8	2.01	1.67	2.06	2.49	2.22	1.94	2.02	2.34	2.45	2.08	1.83	2.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TEMP2035WetWarm {
            get {
                return ResourceManager.GetString("TEMP2035WetWarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	Ann
        ///USC00010008	3.12	2.93	3.61	3.79	4.27	4.28	4.3	4.99	5.14	4.84	4.42	3.18	4.07
        ///USC00010063	4.03	3.87	3.67	4.53	4.96	4.76	4.74	5.02	5.09	5.31	4.64	4.23	4.57
        ///USC00010140	3.35	3.19	3.79	4.32	4.35	4.34	4.36	4.95	5.05	5.15	4.78	3.57	4.27
        ///USC00010252	3.23	3.09	3.6	3.74	4.09	4.15	4.04	4.67	4.93	4.77	4.46	3.22	4.0
        ///USC00010369	3.43	3.3	3.56	4.0	4.43	4.39	4.28	4.99	5.53	5.09	4.61	3.41	4.25
        ///USC00010390	4.07	3.88	3.72	4.57	5.03	4.79	4.79	5.09	5.15	5.37	4.65	4.2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TEMP2060Central {
            get {
                return ResourceManager.GetString("TEMP2060Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	Ann
        ///USC00010008	4.0	3.99	4.12	4.49	5.5	5.66	5.23	4.93	5.23	5.83	5.13	4.61	4.9
        ///USC00010063	3.86	3.97	4.42	4.65	5.47	6.62	6.68	6.29	6.23	6.37	5.41	3.93	5.33
        ///USC00010140	3.71	3.69	4.59	4.84	5.69	6.27	5.99	5.82	5.86	6.29	5.19	3.69	5.13
        ///USC00010252	3.85	4.1	4.74	4.7	5.58	5.81	5.54	5.35	5.53	6.14	5.38	4.07	5.06
        ///USC00010369	3.09	3.83	4.15	4.4	5.41	6.68	6.22	6.09	5.93	6.07	5.26	3.08	5.02
        ///USC00010390	4.46	4.56	4.95	5.04	5.37	5.99	6.48	6.52	6.46	6.41	5.6	5.0	5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TEMP2060HotDry {
            get {
                return ResourceManager.GetString("TEMP2060HotDry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId	Jan	Feb	Mar	Apr	May	Jun	Jul	Aug	Sep	Oct	Nov	Dec	Ann
        ///USC00010008	2.76	3.83	3.04	3.91	4.34	3.81	3.64	3.66	4.24	4.25	3.58	3.51	3.71
        ///USC00010063	3.5	3.9	3.25	3.99	4.84	4.27	3.69	3.82	4.49	4.69	4.01	3.58	4.0
        ///USC00010140	2.64	4.33	3.18	4.25	4.63	4.2	3.61	3.65	4.11	4.31	3.75	3.34	3.83
        ///USC00010252	3.16	3.94	3.09	4.07	4.4	3.95	3.51	3.39	3.93	4.05	3.72	3.27	3.71
        ///USC00010369	2.86	3.92	2.99	4.11	4.6	4.14	3.72	3.86	4.49	4.49	3.73	3.62	3.89
        ///USC00010390	3.51	3.92	3.25	4.03	4.87	4.33	3.79	3.94	4.56	4.78	4.07	3.58 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TEMP2060WetWarm {
            get {
                return ResourceManager.GetString("TEMP2060WetWarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00210	43.005895	-71.013202
        ///00211	43.005895	-71.013202
        ///00212	43.005895	-71.013202
        ///00213	43.005895	-71.013202
        ///00214	43.005895	-71.013202
        ///00215	43.005895	-71.013202
        ///00501	40.922326	-72.637078
        ///00544	40.922326	-72.637078
        ///00601	18.180103	-66.74947
        ///00602	18.363285	-67.18024
        ///00603	18.448619	-67.13422
        ///00604	18.498987	-67.13699
        ///00605	18.465162	-67.141486
        ///00606	18.182151	-66.9588
        ///00607	18.256995	-66.104657
        ///00609	18.142002	-66.273278
        ///00610	18.288319	-67.13604
        ///00611	18.279531	-66.80217
        ///00612	18.449732	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zipcode {
            get {
                return ResourceManager.GetString("zipcode", resourceCulture);
            }
        }
    }
}
